// SPIDEY.h
// Generated by decompiling SPIDEY.COM
// using Reko decompiler version 0.8.0.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals" (C000 (ptr Eq_212) ptrC000))
	globals_t (in globals : (ptr (struct "Globals")))
Eq_2: (segment "Eq_2" (103 word16 w0103) (105 ui16 w0105) (107 word16 w0107) (109 (arr Eq_372) a0109) (526 (arr byte) a0526))
	T_2 (in ds : (ptr Eq_2))
Eq_3: (struct "Eq_3" 0001 (0 word16 w0000))
	T_3 (in di_16 : (memptr (ptr Eq_2) Eq_3))
	T_4 (in 0x0109 : word16)
	T_21 (in di_16 + 0x0001 : word16)
Eq_17: (struct "Eq_17" 0001 (0 word16 w0000))
	T_17 (in di_16 + 0x0000 : word16)
Eq_34: (segment "Eq_34" (2C word16 w002C) (80 (arr byte) a0080) (36C byte b036C) (6C1 byte b06C1) (6C2 (arr byte) a06C2) (6CE word16 w06CE) (6D0 word16 w06D0) (6D2 (ptr Eq_34) ptr06D2) (6D4 (arr byte) a06D4) (714 byte b0714) (717 byte b0717))
	T_34 (in cs : selector)
	T_37 (in Mem54[ss:0x0815:word16] : word16)
	T_38 (in ds_56 : (ptr Eq_34))
	T_40 (in Mem54[ss:0x0815:selector] : selector)
	T_64 (in Mem93[ss:0x0815:word16] : word16)
	T_65 (in es_94 : (ptr Eq_34))
	T_67 (in Mem93[ss:0x0815:selector] : selector)
	T_94 (in es : selector)
	T_111 (in ds : selector)
	T_157 (in Mem148[ss:0x0815:word16] : word16)
	T_159 (in Mem148[ss:0x0815:word16] : word16)
	T_161 (in Mem151[ds_56:0x06D2:word16] : word16)
	T_170 (in Mem157[ss:0x0815:word16] : word16)
	T_171 (in es_158 : (ptr Eq_34))
	T_173 (in Mem157[ss:0x0815:selector] : selector)
	T_175 (in Mem162[ss:0x0815:word16] : word16)
	T_176 (in ds_163 : (ptr Eq_34))
	T_178 (in Mem162[ss:0x0815:selector] : selector)
	T_204 (in Mem188[ss:0x0815:word16] : word16)
	T_219 (in Mem198[ss:0x0815:word16] : word16)
	T_233 (in Mem208[ss:0x0815:word16] : word16)
	T_247 (in Mem219[ss:0x0815:word16] : word16)
	T_254 (in Mem219[ss:0x0815:selector] : selector)
	T_259 (in Mem226[ss:0x0815:word16] : word16)
	T_266 (in Mem226[ss:0x0815:selector] : selector)
	T_271 (in Mem233[ss:0x0815:word16] : word16)
	T_278 (in Mem233[ss:0x0815:selector] : selector)
	T_283 (in Mem240[ss:0x0815:word16] : word16)
	T_290 (in Mem240[ss:0x0815:selector] : selector)
	T_295 (in Mem246[ss:0x0815:word16] : word16)
	T_296 (in ds_247 : (ptr Eq_34))
	T_298 (in Mem246[ss:0x0815:selector] : selector)
	T_300 (in Mem250[ss:0x0815:word16] : word16)
	T_310 (in Mem250[ss:0x0815:selector] : selector)
Eq_35: (segment "Eq_35" (815 (ptr Eq_34) ptr0815))
	T_35 (in ss : selector)
Eq_44: (fn void ((ptr char)))
	T_44 (in msdos_display_string : ptr32)
	T_45 (in signature of msdos_display_string : void)
Eq_51: (fn byte ())
	T_51 (in msdos_character_input_without_echo : ptr32)
	T_52 (in signature of msdos_character_input_without_echo : void)
Eq_58: (fn void (byte))
	T_58 (in msdos_terminate : ptr32)
	T_59 (in signature of msdos_terminate : void)
Eq_78: (fn void (ui8))
	T_78 (in msdos_write_console_char : ptr32)
	T_79 (in signature of msdos_write_console_char : void)
Eq_86: (fn void (byte))
	T_86 (in msdos_terminate : ptr32)
	T_87 (in signature of msdos_terminate : void)
Eq_92: (fn bool ((ptr Eq_34), word16, ptr16))
	T_92 (in msdos_resize_memory_block : ptr32)
	T_93 (in signature of msdos_resize_memory_block : void)
Eq_103: (fn byte ())
	T_103 (in msdos_get_current_default_drive : ptr32)
	T_104 (in signature of msdos_get_current_default_drive : void)
Eq_108: (fn bool (byte, (ptr Eq_34), word16))
	T_108 (in msdos_get_current_directory : ptr32)
	T_109 (in signature of msdos_get_current_directory : void)
Eq_206: (fn word32 (byte))
	T_206 (in msdos_get_interrupt_vector : ptr32)
	T_207 (in signature of msdos_get_interrupt_vector : void)
Eq_211: (segment "Eq_211")
	T_211 (in SLICE(es_bx_192, selector, 16) : selector)
	T_214 (in Mem195[0x0C00:0x06AE:word16] : word16)
	T_356 (in Mem250[0x0C00:0x06AE:selector] : selector)
Eq_212: (segment "Eq_212" (459 word16 w0459) (45B (ptr Eq_226) ptr045B) (51E word16 w051E) (520 (ptr Eq_240) ptr0520) (6AC word16 w06AC) (6AE (ptr Eq_211) ptr06AE))
	T_212 (in 0x0C00 : selector)
Eq_221: (fn word32 (byte))
	T_221 (in msdos_get_interrupt_vector : ptr32)
	T_222 (in signature of msdos_get_interrupt_vector : void)
Eq_226: (segment "Eq_226")
	T_226 (in SLICE(es_bx_202, selector, 16) : selector)
	T_228 (in Mem205[0x0C00:0x045B:word16] : word16)
	T_334 (in Mem250[0x0C00:0x045B:selector] : selector)
Eq_235: (fn word32 (byte))
	T_235 (in msdos_get_interrupt_vector : ptr32)
	T_236 (in signature of msdos_get_interrupt_vector : void)
Eq_240: (segment "Eq_240")
	T_240 (in SLICE(es_bx_212, selector, 16) : selector)
	T_242 (in Mem215[0x0C00:0x0520:word16] : word16)
	T_345 (in Mem250[0x0C00:0x0520:selector] : selector)
Eq_248: (fn void (byte, (ptr code)))
	T_248 (in msdos_set_interrupt_vector : ptr32)
	T_249 (in signature of msdos_set_interrupt_vector : void)
Eq_260: (fn void (byte, (ptr code)))
	T_260 (in msdos_set_interrupt_vector : ptr32)
	T_261 (in signature of msdos_set_interrupt_vector : void)
Eq_272: (fn void (byte, (ptr code)))
	T_272 (in msdos_set_interrupt_vector : ptr32)
	T_273 (in signature of msdos_set_interrupt_vector : void)
Eq_284: (fn void (byte, (ptr code)))
	T_284 (in msdos_set_interrupt_vector : ptr32)
	T_285 (in signature of msdos_set_interrupt_vector : void)
Eq_301: (fn bool (byte, word32, ptr32))
	T_301 (in msdos_exec : ptr32)
	T_302 (in signature of msdos_exec : void)
Eq_328: (fn void (byte, (ptr code)))
	T_328 (in msdos_set_interrupt_vector : ptr32)
	T_329 (in signature of msdos_set_interrupt_vector : void)
Eq_339: (fn void (byte, (ptr code)))
	T_339 (in msdos_set_interrupt_vector : ptr32)
	T_340 (in signature of msdos_set_interrupt_vector : void)
Eq_350: (fn void (byte, (ptr code)))
	T_350 (in msdos_set_interrupt_vector : ptr32)
	T_351 (in signature of msdos_set_interrupt_vector : void)
Eq_361: (fn byte (byte))
	T_361 (in msdos_flush_buffer_and_read_stdin : ptr32)
	T_362 (in signature of msdos_flush_buffer_and_read_stdin : void)
Eq_366: (fn void ((ptr char)))
	T_366 (in msdos_display_string : ptr32)
	T_367 (in signature of msdos_display_string : void)
Eq_372: (struct "Eq_372" 0001 (0 word16 w0000))
	T_372
	T_373
// Type Variables ////////////
globals_t: (in globals : (ptr (struct "Globals")))
  Class: Eq_1
  DataType: (ptr Eq_1)
  OrigDataType: (ptr (struct "Globals"))
T_2: (in ds : (ptr Eq_2))
  Class: Eq_2
  DataType: (ptr Eq_2)
  OrigDataType: (ptr (segment (103 T_27 t0103) (105 T_32 t0105) (107 T_7 t0107) (109 (arr T_372) a0109) (526 (arr T_374) a0526)))
T_3: (in di_16 : (memptr (ptr Eq_2) Eq_3))
  Class: Eq_3
  DataType: (memptr (ptr Eq_2) Eq_3)
  OrigDataType: (memptr T_2 (struct 0001 (0 word16 w0000)))
T_4: (in 0x0109 : word16)
  Class: Eq_3
  DataType: (memptr (ptr Eq_2) Eq_3)
  OrigDataType: word16
T_5: (in cx_17 : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_6: (in 0x0107 : word16)
  Class: Eq_6
  DataType: (memptr (ptr Eq_2) word16)
  OrigDataType: (memptr T_2 (struct (0 T_7 t0000)))
T_7: (in Mem0[ds:0x0107:word16] : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_8: (in ax_18 : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_9: (in 0x0000 : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_10: (in bx_10 : ui16)
  Class: Eq_10
  DataType: ui16
  OrigDataType: ui16
T_11: (in 0x0000 : word16)
  Class: Eq_10
  DataType: ui16
  OrigDataType: word16
T_12: (in 0x0000 : word16)
  Class: Eq_12
  DataType: word16
  OrigDataType: word16
T_13: (in di_16 + 0x0000 : word16)
  Class: Eq_13
  DataType: word16
  OrigDataType: word16
T_14: (in Mem0[ds:di_16 + 0x0000:word16] : word16)
  Class: Eq_14
  DataType: word16
  OrigDataType: word16
T_15: (in ax_18 + (ds->*di_16).w0000 : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_16: (in 0x0000 : word16)
  Class: Eq_16
  DataType: word16
  OrigDataType: word16
T_17: (in di_16 + 0x0000 : word16)
  Class: Eq_17
  DataType: (memptr (ptr Eq_2) Eq_17)
  OrigDataType: (memptr T_2 (struct 0001 (0 word16 w0000)))
T_18: (in Mem0[ds:di_16 + 0x0000:word16] : word16)
  Class: Eq_14
  DataType: word16
  OrigDataType: word16
T_19: (in bx_10 ^ (ds->*di_16).w0000 : word16)
  Class: Eq_10
  DataType: ui16
  OrigDataType: ui16
T_20: (in 0x0001 : word16)
  Class: Eq_20
  DataType: int16
  OrigDataType: int16
T_21: (in di_16 + 0x0001 : word16)
  Class: Eq_3
  DataType: (memptr (ptr Eq_2) Eq_3)
  OrigDataType: (memptr T_2 (struct 0001 (0 word16 w0000)))
T_22: (in 0x0001 : word16)
  Class: Eq_22
  DataType: word16
  OrigDataType: word16
T_23: (in cx_17 - 0x0001 : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_24: (in 0x0000 : word16)
  Class: Eq_5
  DataType: word16
  OrigDataType: word16
T_25: (in cx_17 != 0x0000 : bool)
  Class: Eq_25
  DataType: bool
  OrigDataType: bool
T_26: (in 0x0103 : word16)
  Class: Eq_26
  DataType: (memptr (ptr Eq_2) word16)
  OrigDataType: (memptr T_2 (struct (0 T_27 t0000)))
T_27: (in Mem0[ds:0x0103:word16] : word16)
  Class: Eq_8
  DataType: word16
  OrigDataType: word16
T_28: (in ax_18 != ds->w0103 : bool)
  Class: Eq_28
  DataType: bool
  OrigDataType: bool
T_29: (in di_33 : (memptr (ptr Eq_2) byte))
  Class: Eq_29
  DataType: (memptr (ptr Eq_2) byte)
  OrigDataType: (memptr T_2 (struct 0001 (0 byte b0000)))
T_30: (in 0x0526 : word16)
  Class: Eq_29
  DataType: (memptr (ptr Eq_2) byte)
  OrigDataType: word16
T_31: (in 0x0105 : word16)
  Class: Eq_31
  DataType: (memptr (ptr Eq_2) ui16)
  OrigDataType: (memptr T_2 (struct (0 T_32 t0000)))
T_32: (in Mem0[ds:0x0105:word16] : word16)
  Class: Eq_10
  DataType: ui16
  OrigDataType: word16
T_33: (in bx_10 != ds->w0105 : bool)
  Class: Eq_33
  DataType: bool
  OrigDataType: bool
T_34: (in cs : selector)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment))
T_35: (in ss : selector)
  Class: Eq_35
  DataType: (ptr Eq_35)
  OrigDataType: (ptr (segment (815 T_34 t0815)))
T_36: (in 0x0815 : word16)
  Class: Eq_36
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_37 t0000)))
T_37: (in Mem54[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_38: (in ds_56 : (ptr Eq_34))
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment (2C T_166 t002C) (36C T_43 t036C) (6C2 (arr T_375) a06C2) (6CE T_168 t06CE) (6D0 T_164 t06D0) (6D2 T_161 t06D2) (714 T_102 t0714) (717 T_119 t0717)))
T_39: (in 0x0815 : word16)
  Class: Eq_39
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_40 t0000)))
T_40: (in Mem54[ss:0x0815:selector] : selector)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment))
T_41: (in 0x0D : byte)
  Class: Eq_41
  DataType: byte
  OrigDataType: byte
T_42: (in 0x036C : word16)
  Class: Eq_42
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_38 (struct (0 T_43 t0000)))
T_43: (in Mem58[ds_56:0x036C:byte] : byte)
  Class: Eq_41
  DataType: byte
  OrigDataType: byte
T_44: (in msdos_display_string : ptr32)
  Class: Eq_44
  DataType: (ptr Eq_44)
  OrigDataType: (ptr (fn T_49 (T_48)))
T_45: (in signature of msdos_display_string : void)
  Class: Eq_44
  DataType: (ptr Eq_44)
  OrigDataType: 
T_46: (in ds_dx : (ptr char))
  Class: Eq_46
  DataType: (ptr char)
  OrigDataType: 
T_47: (in 0x010A : word16)
  Class: Eq_47
  DataType: word16
  OrigDataType: word16
T_48: (in SEQ(ds_56, 0x010A) : word32)
  Class: Eq_46
  DataType: (ptr char)
  OrigDataType: (ptr char)
T_49: (in msdos_display_string(ds_56->a0080 + 138) : void)
  Class: Eq_49
  DataType: void
  OrigDataType: void
T_50: (in al_63 : byte)
  Class: Eq_50
  DataType: byte
  OrigDataType: byte
T_51: (in msdos_character_input_without_echo : ptr32)
  Class: Eq_51
  DataType: (ptr Eq_51)
  OrigDataType: (ptr (fn T_53 ()))
T_52: (in signature of msdos_character_input_without_echo : void)
  Class: Eq_51
  DataType: (ptr Eq_51)
  OrigDataType: 
T_53: (in msdos_character_input_without_echo() : byte)
  Class: Eq_50
  DataType: byte
  OrigDataType: byte
T_54: (in 0x03 : byte)
  Class: Eq_50
  DataType: byte
  OrigDataType: byte
T_55: (in al_63 != 0x03 : bool)
  Class: Eq_55
  DataType: bool
  OrigDataType: bool
T_56: (in 0x1B : byte)
  Class: Eq_50
  DataType: byte
  OrigDataType: byte
T_57: (in al_63 != 0x1B : bool)
  Class: Eq_57
  DataType: bool
  OrigDataType: bool
T_58: (in msdos_terminate : ptr32)
  Class: Eq_58
  DataType: (ptr Eq_58)
  OrigDataType: (ptr (fn T_62 (T_61)))
T_59: (in signature of msdos_terminate : void)
  Class: Eq_58
  DataType: (ptr Eq_58)
  OrigDataType: 
T_60: (in al : byte)
  Class: Eq_60
  DataType: byte
  OrigDataType: 
T_61: (in 0x00 : byte)
  Class: Eq_60
  DataType: byte
  OrigDataType: byte
T_62: (in msdos_terminate(0x00) : void)
  Class: Eq_62
  DataType: void
  OrigDataType: void
T_63: (in 0x0815 : word16)
  Class: Eq_63
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_64 t0000)))
T_64: (in Mem93[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_65: (in es_94 : (ptr Eq_34))
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment))
T_66: (in 0x0815 : word16)
  Class: Eq_66
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_67 t0000)))
T_67: (in Mem93[ss:0x0815:selector] : selector)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment))
T_68: (in bx_105 : word16)
  Class: Eq_68
  DataType: word16
  OrigDataType: word16
T_69: (in 0x0081 : word16)
  Class: Eq_68
  DataType: word16
  OrigDataType: word16
T_70: (in dl_41 : ui8)
  Class: Eq_70
  DataType: ui8
  OrigDataType: ui8
T_71: (in 0x0000 : word16)
  Class: Eq_71
  DataType: word16
  OrigDataType: word16
T_72: (in di_33 + 0x0000 : word16)
  Class: Eq_72
  DataType: word16
  OrigDataType: word16
T_73: (in Mem0[ds:di_33 + 0x0000:byte] : byte)
  Class: Eq_73
  DataType: byte
  OrigDataType: byte
T_74: (in 0x4D : byte)
  Class: Eq_74
  DataType: byte
  OrigDataType: byte
T_75: (in ds->*di_33 ^ 0x4D : byte)
  Class: Eq_75
  DataType: ui8
  OrigDataType: ui8
T_76: (in 0x59 : byte)
  Class: Eq_76
  DataType: ui8
  OrigDataType: ui8
T_77: (in (ds->*di_33 ^ 0x4D) - 0x59 : byte)
  Class: Eq_70
  DataType: ui8
  OrigDataType: ui8
T_78: (in msdos_write_console_char : ptr32)
  Class: Eq_78
  DataType: (ptr Eq_78)
  OrigDataType: (ptr (fn T_81 (T_70)))
T_79: (in signature of msdos_write_console_char : void)
  Class: Eq_78
  DataType: (ptr Eq_78)
  OrigDataType: 
T_80: (in dl : byte)
  Class: Eq_70
  DataType: ui8
  OrigDataType: 
T_81: (in msdos_write_console_char(dl_41) : void)
  Class: Eq_81
  DataType: void
  OrigDataType: void
T_82: (in 0x0001 : word16)
  Class: Eq_82
  DataType: int16
  OrigDataType: int16
T_83: (in di_33 + 0x0001 : word16)
  Class: Eq_29
  DataType: (memptr (ptr Eq_2) byte)
  OrigDataType: (memptr T_2 (struct 0001 (0 byte b0000)))
T_84: (in 0x00 : byte)
  Class: Eq_70
  DataType: ui8
  OrigDataType: byte
T_85: (in dl_41 != 0x00 : bool)
  Class: Eq_85
  DataType: bool
  OrigDataType: bool
T_86: (in msdos_terminate : ptr32)
  Class: Eq_86
  DataType: (ptr Eq_86)
  OrigDataType: (ptr (fn T_90 (T_89)))
T_87: (in signature of msdos_terminate : void)
  Class: Eq_86
  DataType: (ptr Eq_86)
  OrigDataType: 
T_88: (in al : byte)
  Class: Eq_88
  DataType: byte
  OrigDataType: 
T_89: (in 0xFF : byte)
  Class: Eq_88
  DataType: byte
  OrigDataType: byte
T_90: (in msdos_terminate(0xFF) : void)
  Class: Eq_90
  DataType: void
  OrigDataType: void
T_91: (in bx_300 : word16)
  Class: Eq_68
  DataType: word16
  OrigDataType: word16
T_92: (in msdos_resize_memory_block : ptr32)
  Class: Eq_92
  DataType: (ptr Eq_92)
  OrigDataType: (ptr (fn T_100 (T_65, T_98, T_99)))
T_93: (in signature of msdos_resize_memory_block : void)
  Class: Eq_92
  DataType: (ptr Eq_92)
  OrigDataType: 
T_94: (in es : selector)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: 
T_95: (in bx : word16)
  Class: Eq_95
  DataType: word16
  OrigDataType: 
T_96: (in bxOut : ptr16)
  Class: Eq_96
  DataType: ptr16
  OrigDataType: 
T_97: (in 0x0001 : word16)
  Class: Eq_97
  DataType: word16
  OrigDataType: word16
T_98: (in bx_300 + 0x0001 : word16)
  Class: Eq_95
  DataType: word16
  OrigDataType: word16
T_99: (in out bx_105 : mp16)
  Class: Eq_96
  DataType: ptr16
  OrigDataType: ptr16
T_100: (in msdos_resize_memory_block(es_94, bx_300 + 0x0001, out bx_105) : bool)
  Class: Eq_100
  DataType: bool
  OrigDataType: bool
T_101: (in 0x0714 : word16)
  Class: Eq_101
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_38 (struct (0 T_102 t0000)))
T_102: (in Mem93[ds_56:0x0714:byte] : byte)
  Class: Eq_102
  DataType: byte
  OrigDataType: byte
T_103: (in msdos_get_current_default_drive : ptr32)
  Class: Eq_103
  DataType: (ptr Eq_103)
  OrigDataType: (ptr (fn T_105 ()))
T_104: (in signature of msdos_get_current_default_drive : void)
  Class: Eq_103
  DataType: (ptr Eq_103)
  OrigDataType: 
T_105: (in msdos_get_current_default_drive() : byte)
  Class: Eq_105
  DataType: byte
  OrigDataType: byte
T_106: (in ds_56->b0714 + msdos_get_current_default_drive() : byte)
  Class: Eq_102
  DataType: byte
  OrigDataType: byte
T_107: (in Mem109[ds_56:0x0714:byte] : byte)
  Class: Eq_102
  DataType: byte
  OrigDataType: byte
T_108: (in msdos_get_current_directory : ptr32)
  Class: Eq_108
  DataType: (ptr Eq_108)
  OrigDataType: (ptr (fn T_115 (T_113, T_38, T_114)))
T_109: (in signature of msdos_get_current_directory : void)
  Class: Eq_108
  DataType: (ptr Eq_108)
  OrigDataType: 
T_110: (in dl : byte)
  Class: Eq_110
  DataType: byte
  OrigDataType: 
T_111: (in ds : selector)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: 
T_112: (in dx : word16)
  Class: Eq_112
  DataType: word16
  OrigDataType: 
T_113: (in 0x00 : byte)
  Class: Eq_110
  DataType: byte
  OrigDataType: byte
T_114: (in 0x0100 : word16)
  Class: Eq_112
  DataType: word16
  OrigDataType: word16
T_115: (in msdos_get_current_directory(0x00, ds_56, 0x0100) : bool)
  Class: Eq_115
  DataType: bool
  OrigDataType: bool
T_116: (in di_116 : (memptr (ptr Eq_34) byte))
  Class: Eq_116
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_34 (struct 0001 (0 byte b0000)))
T_117: (in 0x0717 : word16)
  Class: Eq_116
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: word16
T_118: (in 0x0717 : word16)
  Class: Eq_118
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_38 (struct (0 T_119 t0000)))
T_119: (in Mem109[ds_56:0x0717:byte] : byte)
  Class: Eq_119
  DataType: byte
  OrigDataType: byte
T_120: (in 0x00 : byte)
  Class: Eq_119
  DataType: byte
  OrigDataType: byte
T_121: (in ds_56->b0717 == 0x00 : bool)
  Class: Eq_121
  DataType: bool
  OrigDataType: bool
T_122: (in si_124 : (memptr (ptr Eq_34) byte))
  Class: Eq_122
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_38 (struct 0001 (0 byte b0000)))
T_123: (in 0x06C1 : word16)
  Class: Eq_122
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: word16
T_124: (in cx_125 : word16)
  Class: Eq_124
  DataType: word16
  OrigDataType: word16
T_125: (in 0x0000 : word16)
  Class: Eq_124
  DataType: word16
  OrigDataType: word16
T_126: (in cx_282 : word16)
  Class: Eq_126
  DataType: word16
  OrigDataType: word16
T_127: (in 0x0100 : word16)
  Class: Eq_126
  DataType: word16
  OrigDataType: word16
T_128: (in 0x5C : byte)
  Class: Eq_128
  DataType: byte
  OrigDataType: byte
T_129: (in 0x0001 : word16)
  Class: Eq_129
  DataType: ui16
  OrigDataType: ui16
T_130: (in di_116 - 0x0001 : word16)
  Class: Eq_130
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_38 (struct (0 T_133 t0000)))
T_131: (in 0x0000 : word16)
  Class: Eq_131
  DataType: word16
  OrigDataType: word16
T_132: (in di_116 - 0x0001 + 0x0000 : word16)
  Class: Eq_132
  DataType: word16
  OrigDataType: word16
T_133: (in Mem294[ds_56:di_116 - 0x0001 + 0x0000:byte] : byte)
  Class: Eq_128
  DataType: byte
  OrigDataType: byte
T_134: (in 0x0001 : word16)
  Class: Eq_134
  DataType: int16
  OrigDataType: int16
T_135: (in di_116 + 0x0001 : word16)
  Class: Eq_116
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_38 (struct (0 T_133 t0000)))
T_136: (in 0x0001 : word16)
  Class: Eq_136
  DataType: word16
  OrigDataType: word16
T_137: (in cx_282 - 0x0001 : word16)
  Class: Eq_126
  DataType: word16
  OrigDataType: word16
T_138: (in 0x00 : byte)
  Class: Eq_138
  DataType: byte
  OrigDataType: byte
T_139: (in 0x0000 : word16)
  Class: Eq_139
  DataType: word16
  OrigDataType: word16
T_140: (in di_116 + 0x0000 : word16)
  Class: Eq_140
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_38 (struct (0 T_133 t0000)))
T_141: (in Mem109[es_94:di_116 + 0x0000:byte] : byte)
  Class: Eq_138
  DataType: byte
  OrigDataType: byte
T_142: (in 0x00 == es_94->*di_116 : bool)
  Class: Eq_142
  DataType: bool
  OrigDataType: bool
T_143: (in 0x0000 : word16)
  Class: Eq_126
  DataType: word16
  OrigDataType: word16
T_144: (in cx_282 == 0x0000 : bool)
  Class: Eq_144
  DataType: bool
  OrigDataType: bool
T_145: (in 0x0001 : word16)
  Class: Eq_145
  DataType: word16
  OrigDataType: word16
T_146: (in cx_125 + 0x0001 : word16)
  Class: Eq_124
  DataType: word16
  OrigDataType: word16
T_147: (in 0x0001 : word16)
  Class: Eq_147
  DataType: word16
  OrigDataType: word16
T_148: (in si_124 + 0x0001 : word16)
  Class: Eq_122
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: word16
T_149: (in 0x0000 : word16)
  Class: Eq_149
  DataType: word16
  OrigDataType: word16
T_150: (in si_124 + 0x0000 : word16)
  Class: Eq_150
  DataType: word16
  OrigDataType: word16
T_151: (in Mem109[ds_56:si_124 + 0x0000:byte] : byte)
  Class: Eq_151
  DataType: byte
  OrigDataType: byte
T_152: (in 0x00 : byte)
  Class: Eq_151
  DataType: byte
  OrigDataType: byte
T_153: (in ds_56->*si_124 != 0x00 : bool)
  Class: Eq_153
  DataType: bool
  OrigDataType: bool
T_154: (in si_136 : (memptr (ptr Eq_34) byte))
  Class: Eq_154
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_38 (struct 0001 (0 byte b0000)))
T_155: (in 0x06C2 : word16)
  Class: Eq_154
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: word16
T_156: (in 0x0815 : word16)
  Class: Eq_156
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_157 t0000)))
T_157: (in Mem148[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_158: (in 0x0815 : word16)
  Class: Eq_158
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_159 t0000)))
T_159: (in Mem148[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_160: (in 0x06D2 : word16)
  Class: Eq_160
  DataType: (memptr (ptr Eq_34) (ptr Eq_34))
  OrigDataType: (memptr T_38 (struct (0 T_161 t0000)))
T_161: (in Mem151[ds_56:0x06D2:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_162: (in 0x06D4 : word16)
  Class: Eq_162
  DataType: word16
  OrigDataType: word16
T_163: (in 0x06D0 : word16)
  Class: Eq_163
  DataType: (memptr (ptr Eq_34) word16)
  OrigDataType: (memptr T_38 (struct (0 T_164 t0000)))
T_164: (in Mem153[ds_56:0x06D0:word16] : word16)
  Class: Eq_162
  DataType: word16
  OrigDataType: word16
T_165: (in 0x002C : word16)
  Class: Eq_165
  DataType: (memptr (ptr Eq_34) word16)
  OrigDataType: (memptr T_38 (struct (0 T_166 t0000)))
T_166: (in Mem153[ds_56:0x002C:word16] : word16)
  Class: Eq_166
  DataType: word16
  OrigDataType: word16
T_167: (in 0x06CE : word16)
  Class: Eq_167
  DataType: (memptr (ptr Eq_34) word16)
  OrigDataType: (memptr T_38 (struct (0 T_168 t0000)))
T_168: (in Mem155[ds_56:0x06CE:word16] : word16)
  Class: Eq_166
  DataType: word16
  OrigDataType: word16
T_169: (in 0x0815 : word16)
  Class: Eq_169
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_170 t0000)))
T_170: (in Mem157[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_171: (in es_158 : (ptr Eq_34))
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment (6D4 (arr T_378) a06D4)))
T_172: (in 0x0815 : word16)
  Class: Eq_172
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_173 t0000)))
T_173: (in Mem157[ss:0x0815:selector] : selector)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment))
T_174: (in 0x0815 : word16)
  Class: Eq_174
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_175 t0000)))
T_175: (in Mem162[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_176: (in ds_163 : (ptr Eq_34))
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment (80 (arr T_185) a0080)))
T_177: (in 0x0815 : word16)
  Class: Eq_177
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_178 t0000)))
T_178: (in Mem162[ss:0x0815:selector] : selector)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment))
T_179: (in si_166 : (memptr (ptr Eq_34) byte))
  Class: Eq_179
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_176 (struct 0001 (0 byte b0000)))
T_180: (in 0x0080 : word16)
  Class: Eq_179
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: word16
T_181: (in di_167 : (memptr (ptr Eq_34) byte))
  Class: Eq_181
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_171 (struct 0001 (0 byte b0000)))
T_182: (in 0x06D4 : word16)
  Class: Eq_181
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: word16
T_183: (in cx_173 : word16)
  Class: Eq_183
  DataType: word16
  OrigDataType: word16
T_184: (in 0x0080 : word16)
  Class: Eq_184
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_176 (struct (0 T_185 t0000)))
T_185: (in Mem162[ds_163:0x0080:byte] : byte)
  Class: Eq_185
  DataType: byte
  OrigDataType: byte
T_186: (in (word16) ds_163->a0080[0] : word16)
  Class: Eq_186
  DataType: word16
  OrigDataType: word16
T_187: (in 0x0002 : word16)
  Class: Eq_187
  DataType: word16
  OrigDataType: word16
T_188: (in (word16) ds_163->a0080[0] + 0x0002 : word16)
  Class: Eq_183
  DataType: word16
  OrigDataType: word16
T_189: (in 0x0000 : word16)
  Class: Eq_189
  DataType: word16
  OrigDataType: word16
T_190: (in si_136 + 0x0000 : word16)
  Class: Eq_190
  DataType: word16
  OrigDataType: word16
T_191: (in Mem109[ds_56:si_136 + 0x0000:byte] : byte)
  Class: Eq_151
  DataType: byte
  OrigDataType: byte
T_192: (in 0x0000 : word16)
  Class: Eq_192
  DataType: word16
  OrigDataType: word16
T_193: (in di_116 + 0x0000 : word16)
  Class: Eq_193
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_34 (struct 0001 (0 byte b0000)))
T_194: (in Mem142[es_94:di_116 + 0x0000:byte] : byte)
  Class: Eq_151
  DataType: byte
  OrigDataType: byte
T_195: (in 0x0001 : word16)
  Class: Eq_195
  DataType: int16
  OrigDataType: int16
T_196: (in si_136 + 0x0001 : word16)
  Class: Eq_154
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_38 (struct 0001 (0 byte b0000)))
T_197: (in 0x0001 : word16)
  Class: Eq_197
  DataType: int16
  OrigDataType: int16
T_198: (in di_116 + 0x0001 : word16)
  Class: Eq_116
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_34 (struct 0001 (0 byte b0000)))
T_199: (in 0x0001 : word16)
  Class: Eq_199
  DataType: word16
  OrigDataType: word16
T_200: (in cx_125 - 0x0001 : word16)
  Class: Eq_124
  DataType: word16
  OrigDataType: word16
T_201: (in 0x0000 : word16)
  Class: Eq_124
  DataType: word16
  OrigDataType: word16
T_202: (in cx_125 == 0x0000 : bool)
  Class: Eq_202
  DataType: bool
  OrigDataType: bool
T_203: (in 0x0815 : word16)
  Class: Eq_203
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_204 t0000)))
T_204: (in Mem188[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_205: (in es_bx_192 : word32)
  Class: Eq_205
  DataType: word32
  OrigDataType: word32
T_206: (in msdos_get_interrupt_vector : ptr32)
  Class: Eq_206
  DataType: (ptr Eq_206)
  OrigDataType: (ptr (fn T_210 (T_209)))
T_207: (in signature of msdos_get_interrupt_vector : void)
  Class: Eq_206
  DataType: (ptr Eq_206)
  OrigDataType: 
T_208: (in al : byte)
  Class: Eq_208
  DataType: byte
  OrigDataType: 
T_209: (in 0x1B : byte)
  Class: Eq_208
  DataType: byte
  OrigDataType: byte
T_210: (in msdos_get_interrupt_vector(0x1B) : word32)
  Class: Eq_205
  DataType: word32
  OrigDataType: word32
T_211: (in SLICE(es_bx_192, selector, 16) : selector)
  Class: Eq_211
  DataType: (ptr Eq_211)
  OrigDataType: (ptr (segment))
T_212: (in 0x0C00 : selector)
  Class: Eq_212
  DataType: (ptr Eq_212)
  OrigDataType: (ptr (segment (459 T_229 t0459) (45B T_226 t045B) (51E T_243 t051E) (520 T_240 t0520) (6AC T_215 t06AC) (6AE T_211 t06AE)))
T_213: (in 0x06AE : word16)
  Class: Eq_213
  DataType: (memptr (ptr Eq_212) (ptr Eq_211))
  OrigDataType: (memptr T_212 (struct (0 T_214 t0000)))
T_214: (in Mem195[0x0C00:0x06AE:word16] : word16)
  Class: Eq_211
  DataType: (ptr Eq_211)
  OrigDataType: word16
T_215: (in (word16) es_bx_192 : word16)
  Class: Eq_215
  DataType: word16
  OrigDataType: word16
T_216: (in 0x06AC : word16)
  Class: Eq_216
  DataType: (memptr (ptr Eq_212) word16)
  OrigDataType: (memptr T_212 (struct (0 T_217 t0000)))
T_217: (in Mem196[0x0C00:0x06AC:word16] : word16)
  Class: Eq_215
  DataType: word16
  OrigDataType: word16
T_218: (in 0x0815 : word16)
  Class: Eq_218
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_219 t0000)))
T_219: (in Mem198[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_220: (in es_bx_202 : word32)
  Class: Eq_220
  DataType: word32
  OrigDataType: word32
T_221: (in msdos_get_interrupt_vector : ptr32)
  Class: Eq_221
  DataType: (ptr Eq_221)
  OrigDataType: (ptr (fn T_225 (T_224)))
T_222: (in signature of msdos_get_interrupt_vector : void)
  Class: Eq_221
  DataType: (ptr Eq_221)
  OrigDataType: 
T_223: (in al : byte)
  Class: Eq_223
  DataType: byte
  OrigDataType: 
T_224: (in 0x10 : byte)
  Class: Eq_223
  DataType: byte
  OrigDataType: byte
T_225: (in msdos_get_interrupt_vector(0x10) : word32)
  Class: Eq_220
  DataType: word32
  OrigDataType: word32
T_226: (in SLICE(es_bx_202, selector, 16) : selector)
  Class: Eq_226
  DataType: (ptr Eq_226)
  OrigDataType: (ptr (segment))
T_227: (in 0x045B : word16)
  Class: Eq_227
  DataType: (memptr (ptr Eq_212) (ptr Eq_226))
  OrigDataType: (memptr T_212 (struct (0 T_228 t0000)))
T_228: (in Mem205[0x0C00:0x045B:word16] : word16)
  Class: Eq_226
  DataType: (ptr Eq_226)
  OrigDataType: word16
T_229: (in (word16) es_bx_202 : word16)
  Class: Eq_229
  DataType: word16
  OrigDataType: word16
T_230: (in 0x0459 : word16)
  Class: Eq_230
  DataType: (memptr (ptr Eq_212) word16)
  OrigDataType: (memptr T_212 (struct (0 T_231 t0000)))
T_231: (in Mem206[0x0C00:0x0459:word16] : word16)
  Class: Eq_229
  DataType: word16
  OrigDataType: word16
T_232: (in 0x0815 : word16)
  Class: Eq_232
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_233 t0000)))
T_233: (in Mem208[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_234: (in es_bx_212 : word32)
  Class: Eq_234
  DataType: word32
  OrigDataType: word32
T_235: (in msdos_get_interrupt_vector : ptr32)
  Class: Eq_235
  DataType: (ptr Eq_235)
  OrigDataType: (ptr (fn T_239 (T_238)))
T_236: (in signature of msdos_get_interrupt_vector : void)
  Class: Eq_235
  DataType: (ptr Eq_235)
  OrigDataType: 
T_237: (in al : byte)
  Class: Eq_237
  DataType: byte
  OrigDataType: 
T_238: (in 0x09 : byte)
  Class: Eq_237
  DataType: byte
  OrigDataType: byte
T_239: (in msdos_get_interrupt_vector(0x09) : word32)
  Class: Eq_234
  DataType: word32
  OrigDataType: word32
T_240: (in SLICE(es_bx_212, selector, 16) : selector)
  Class: Eq_240
  DataType: (ptr Eq_240)
  OrigDataType: (ptr (segment))
T_241: (in 0x0520 : word16)
  Class: Eq_241
  DataType: (memptr (ptr Eq_212) (ptr Eq_240))
  OrigDataType: (memptr T_212 (struct (0 T_242 t0000)))
T_242: (in Mem215[0x0C00:0x0520:word16] : word16)
  Class: Eq_240
  DataType: (ptr Eq_240)
  OrigDataType: word16
T_243: (in (word16) es_bx_212 : word16)
  Class: Eq_243
  DataType: word16
  OrigDataType: word16
T_244: (in 0x051E : word16)
  Class: Eq_244
  DataType: (memptr (ptr Eq_212) word16)
  OrigDataType: (memptr T_212 (struct (0 T_245 t0000)))
T_245: (in Mem216[0x0C00:0x051E:word16] : word16)
  Class: Eq_243
  DataType: word16
  OrigDataType: word16
T_246: (in 0x0815 : word16)
  Class: Eq_246
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_247 t0000)))
T_247: (in Mem219[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_248: (in msdos_set_interrupt_vector : ptr32)
  Class: Eq_248
  DataType: (ptr Eq_248)
  OrigDataType: (ptr (fn T_257 (T_252, T_256)))
T_249: (in signature of msdos_set_interrupt_vector : void)
  Class: Eq_248
  DataType: (ptr Eq_248)
  OrigDataType: 
T_250: (in al : byte)
  Class: Eq_250
  DataType: byte
  OrigDataType: 
T_251: (in ds_dx : (ptr code))
  Class: Eq_251
  DataType: (ptr code)
  OrigDataType: 
T_252: (in 0x10 : byte)
  Class: Eq_250
  DataType: byte
  OrigDataType: byte
T_253: (in 0x0815 : word16)
  Class: Eq_253
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_254 t0000)))
T_254: (in Mem219[ss:0x0815:selector] : selector)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment))
T_255: (in 0x03A0 : word16)
  Class: Eq_255
  DataType: word16
  OrigDataType: word16
T_256: (in SEQ(Mem219[ss:0x0815:selector], 0x03A0) : word32)
  Class: Eq_251
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_257: (in msdos_set_interrupt_vector(0x10, &ss->ptr0815->b036C + 52) : void)
  Class: Eq_257
  DataType: void
  OrigDataType: void
T_258: (in 0x0815 : word16)
  Class: Eq_258
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_259 t0000)))
T_259: (in Mem226[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_260: (in msdos_set_interrupt_vector : ptr32)
  Class: Eq_260
  DataType: (ptr Eq_260)
  OrigDataType: (ptr (fn T_269 (T_264, T_268)))
T_261: (in signature of msdos_set_interrupt_vector : void)
  Class: Eq_260
  DataType: (ptr Eq_260)
  OrigDataType: 
T_262: (in al : byte)
  Class: Eq_262
  DataType: byte
  OrigDataType: 
T_263: (in ds_dx : (ptr code))
  Class: Eq_263
  DataType: (ptr code)
  OrigDataType: 
T_264: (in 0x09 : byte)
  Class: Eq_262
  DataType: byte
  OrigDataType: byte
T_265: (in 0x0815 : word16)
  Class: Eq_265
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_266 t0000)))
T_266: (in Mem226[ss:0x0815:selector] : selector)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment))
T_267: (in 0x045D : word16)
  Class: Eq_267
  DataType: word16
  OrigDataType: word16
T_268: (in SEQ(Mem226[ss:0x0815:selector], 0x045D) : word32)
  Class: Eq_263
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_269: (in msdos_set_interrupt_vector(0x09, &ss->ptr0815->b036C + 241) : void)
  Class: Eq_269
  DataType: void
  OrigDataType: void
T_270: (in 0x0815 : word16)
  Class: Eq_270
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_271 t0000)))
T_271: (in Mem233[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_272: (in msdos_set_interrupt_vector : ptr32)
  Class: Eq_272
  DataType: (ptr Eq_272)
  OrigDataType: (ptr (fn T_281 (T_276, T_280)))
T_273: (in signature of msdos_set_interrupt_vector : void)
  Class: Eq_272
  DataType: (ptr Eq_272)
  OrigDataType: 
T_274: (in al : byte)
  Class: Eq_274
  DataType: byte
  OrigDataType: 
T_275: (in ds_dx : (ptr code))
  Class: Eq_275
  DataType: (ptr code)
  OrigDataType: 
T_276: (in 0x1B : byte)
  Class: Eq_274
  DataType: byte
  OrigDataType: byte
T_277: (in 0x0815 : word16)
  Class: Eq_277
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_278 t0000)))
T_278: (in Mem233[ss:0x0815:selector] : selector)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment))
T_279: (in 0x039F : word16)
  Class: Eq_279
  DataType: word16
  OrigDataType: word16
T_280: (in SEQ(Mem233[ss:0x0815:selector], 0x039F) : word32)
  Class: Eq_275
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_281: (in msdos_set_interrupt_vector(0x1B, &ss->ptr0815->b036C + 51) : void)
  Class: Eq_281
  DataType: void
  OrigDataType: void
T_282: (in 0x0815 : word16)
  Class: Eq_282
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_283 t0000)))
T_283: (in Mem240[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_284: (in msdos_set_interrupt_vector : ptr32)
  Class: Eq_284
  DataType: (ptr Eq_284)
  OrigDataType: (ptr (fn T_293 (T_288, T_292)))
T_285: (in signature of msdos_set_interrupt_vector : void)
  Class: Eq_284
  DataType: (ptr Eq_284)
  OrigDataType: 
T_286: (in al : byte)
  Class: Eq_286
  DataType: byte
  OrigDataType: 
T_287: (in ds_dx : (ptr code))
  Class: Eq_287
  DataType: (ptr code)
  OrigDataType: 
T_288: (in 0x23 : byte)
  Class: Eq_286
  DataType: byte
  OrigDataType: byte
T_289: (in 0x0815 : word16)
  Class: Eq_289
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_290 t0000)))
T_290: (in Mem240[ss:0x0815:selector] : selector)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment))
T_291: (in 0x039F : word16)
  Class: Eq_291
  DataType: word16
  OrigDataType: word16
T_292: (in SEQ(Mem240[ss:0x0815:selector], 0x039F) : word32)
  Class: Eq_287
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_293: (in msdos_set_interrupt_vector(0x23, &ss->ptr0815->b036C + 51) : void)
  Class: Eq_293
  DataType: void
  OrigDataType: void
T_294: (in 0x0815 : word16)
  Class: Eq_294
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_295 t0000)))
T_295: (in Mem246[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_296: (in ds_247 : (ptr Eq_34))
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment))
T_297: (in 0x0815 : word16)
  Class: Eq_297
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_298 t0000)))
T_298: (in Mem246[ss:0x0815:selector] : selector)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment))
T_299: (in 0x0815 : word16)
  Class: Eq_299
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_300 t0000)))
T_300: (in Mem250[ss:0x0815:word16] : word16)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: word16
T_301: (in msdos_exec : ptr32)
  Class: Eq_301
  DataType: (ptr Eq_301)
  OrigDataType: (ptr (fn T_313 (T_306, T_308, T_312)))
T_302: (in signature of msdos_exec : void)
  Class: Eq_301
  DataType: (ptr Eq_301)
  OrigDataType: 
T_303: (in al : byte)
  Class: Eq_303
  DataType: byte
  OrigDataType: 
T_304: (in ds_dx : word32)
  Class: Eq_304
  DataType: word32
  OrigDataType: 
T_305: (in es_bx : word32)
  Class: Eq_305
  DataType: ptr32
  OrigDataType: 
T_306: (in 0x00 : byte)
  Class: Eq_303
  DataType: byte
  OrigDataType: byte
T_307: (in 0x0714 : word16)
  Class: Eq_307
  DataType: word16
  OrigDataType: word16
T_308: (in SEQ(ds_247, 0x0714) : word32)
  Class: Eq_304
  DataType: word32
  OrigDataType: word32
T_309: (in 0x0815 : word16)
  Class: Eq_309
  DataType: (memptr (ptr Eq_35) (ptr Eq_34))
  OrigDataType: (memptr T_35 (struct (0 T_310 t0000)))
T_310: (in Mem250[ss:0x0815:selector] : selector)
  Class: Eq_34
  DataType: (ptr Eq_34)
  OrigDataType: (ptr (segment))
T_311: (in 0x06CE : word16)
  Class: Eq_311
  DataType: word16
  OrigDataType: word16
T_312: (in SEQ(Mem250[ss:0x0815:selector], 0x06CE) : word32)
  Class: Eq_305
  DataType: ptr32
  OrigDataType: ptr32
T_313: (in msdos_exec(0x00, &ds_247->b0714, &ss->ptr0815->w06CE) : bool)
  Class: Eq_313
  DataType: bool
  OrigDataType: bool
T_314: (in 0x0000 : word16)
  Class: Eq_314
  DataType: word16
  OrigDataType: word16
T_315: (in si_166 + 0x0000 : word16)
  Class: Eq_315
  DataType: word16
  OrigDataType: word16
T_316: (in Mem162[ds_163:si_166 + 0x0000:byte] : byte)
  Class: Eq_316
  DataType: byte
  OrigDataType: byte
T_317: (in 0x0000 : word16)
  Class: Eq_317
  DataType: word16
  OrigDataType: word16
T_318: (in di_167 + 0x0000 : word16)
  Class: Eq_318
  DataType: word16
  OrigDataType: word16
T_319: (in Mem182[es_158:di_167 + 0x0000:byte] : byte)
  Class: Eq_316
  DataType: byte
  OrigDataType: byte
T_320: (in 0x0001 : word16)
  Class: Eq_320
  DataType: int16
  OrigDataType: int16
T_321: (in si_166 + 0x0001 : word16)
  Class: Eq_179
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_176 (struct 0001 (0 byte b0000)))
T_322: (in 0x0001 : word16)
  Class: Eq_322
  DataType: int16
  OrigDataType: int16
T_323: (in di_167 + 0x0001 : word16)
  Class: Eq_181
  DataType: (memptr (ptr Eq_34) byte)
  OrigDataType: (memptr T_171 (struct 0001 (0 byte b0000)))
T_324: (in 0x0001 : word16)
  Class: Eq_324
  DataType: word16
  OrigDataType: word16
T_325: (in cx_173 - 0x0001 : word16)
  Class: Eq_183
  DataType: word16
  OrigDataType: word16
T_326: (in 0x0000 : word16)
  Class: Eq_183
  DataType: word16
  OrigDataType: word16
T_327: (in cx_173 == 0x0000 : bool)
  Class: Eq_327
  DataType: bool
  OrigDataType: bool
T_328: (in msdos_set_interrupt_vector : ptr32)
  Class: Eq_328
  DataType: (ptr Eq_328)
  OrigDataType: (ptr (fn T_338 (T_332, T_337)))
T_329: (in signature of msdos_set_interrupt_vector : void)
  Class: Eq_328
  DataType: (ptr Eq_328)
  OrigDataType: 
T_330: (in al : byte)
  Class: Eq_330
  DataType: byte
  OrigDataType: 
T_331: (in ds_dx : (ptr code))
  Class: Eq_331
  DataType: (ptr code)
  OrigDataType: 
T_332: (in 0x10 : byte)
  Class: Eq_330
  DataType: byte
  OrigDataType: byte
T_333: (in 0x045B : word16)
  Class: Eq_333
  DataType: (memptr (ptr Eq_212) (ptr Eq_226))
  OrigDataType: (memptr T_212 (struct (0 T_334 t0000)))
T_334: (in Mem250[0x0C00:0x045B:selector] : selector)
  Class: Eq_226
  DataType: (ptr Eq_226)
  OrigDataType: (ptr (segment))
T_335: (in 0x0459 : word16)
  Class: Eq_335
  DataType: (memptr (ptr Eq_212) word16)
  OrigDataType: (memptr T_212 (struct (0 T_336 t0000)))
T_336: (in Mem250[0x0C00:0x0459:word16] : word16)
  Class: Eq_229
  DataType: word16
  OrigDataType: word16
T_337: (in SEQ(Mem250[0x0C00:0x045B:selector], Mem250[0x0C00:0x0459:word16]) : word32)
  Class: Eq_331
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_338: (in msdos_set_interrupt_vector(0x10, 0x0C00->w0459) : void)
  Class: Eq_338
  DataType: void
  OrigDataType: void
T_339: (in msdos_set_interrupt_vector : ptr32)
  Class: Eq_339
  DataType: (ptr Eq_339)
  OrigDataType: (ptr (fn T_349 (T_343, T_348)))
T_340: (in signature of msdos_set_interrupt_vector : void)
  Class: Eq_339
  DataType: (ptr Eq_339)
  OrigDataType: 
T_341: (in al : byte)
  Class: Eq_341
  DataType: byte
  OrigDataType: 
T_342: (in ds_dx : (ptr code))
  Class: Eq_342
  DataType: (ptr code)
  OrigDataType: 
T_343: (in 0x09 : byte)
  Class: Eq_341
  DataType: byte
  OrigDataType: byte
T_344: (in 0x0520 : word16)
  Class: Eq_344
  DataType: (memptr (ptr Eq_212) (ptr Eq_240))
  OrigDataType: (memptr T_212 (struct (0 T_345 t0000)))
T_345: (in Mem250[0x0C00:0x0520:selector] : selector)
  Class: Eq_240
  DataType: (ptr Eq_240)
  OrigDataType: (ptr (segment))
T_346: (in 0x051E : word16)
  Class: Eq_346
  DataType: (memptr (ptr Eq_212) word16)
  OrigDataType: (memptr T_212 (struct (0 T_347 t0000)))
T_347: (in Mem250[0x0C00:0x051E:word16] : word16)
  Class: Eq_243
  DataType: word16
  OrigDataType: word16
T_348: (in SEQ(Mem250[0x0C00:0x0520:selector], Mem250[0x0C00:0x051E:word16]) : word32)
  Class: Eq_342
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_349: (in msdos_set_interrupt_vector(0x09, 0x0C00->w051E) : void)
  Class: Eq_349
  DataType: void
  OrigDataType: void
T_350: (in msdos_set_interrupt_vector : ptr32)
  Class: Eq_350
  DataType: (ptr Eq_350)
  OrigDataType: (ptr (fn T_360 (T_354, T_359)))
T_351: (in signature of msdos_set_interrupt_vector : void)
  Class: Eq_350
  DataType: (ptr Eq_350)
  OrigDataType: 
T_352: (in al : byte)
  Class: Eq_352
  DataType: byte
  OrigDataType: 
T_353: (in ds_dx : (ptr code))
  Class: Eq_353
  DataType: (ptr code)
  OrigDataType: 
T_354: (in 0x1B : byte)
  Class: Eq_352
  DataType: byte
  OrigDataType: byte
T_355: (in 0x06AE : word16)
  Class: Eq_355
  DataType: (memptr (ptr Eq_212) (ptr Eq_211))
  OrigDataType: (memptr T_212 (struct (0 T_356 t0000)))
T_356: (in Mem250[0x0C00:0x06AE:selector] : selector)
  Class: Eq_211
  DataType: (ptr Eq_211)
  OrigDataType: (ptr (segment))
T_357: (in 0x06AC : word16)
  Class: Eq_357
  DataType: (memptr (ptr Eq_212) word16)
  OrigDataType: (memptr T_212 (struct (0 T_358 t0000)))
T_358: (in Mem250[0x0C00:0x06AC:word16] : word16)
  Class: Eq_215
  DataType: word16
  OrigDataType: word16
T_359: (in SEQ(Mem250[0x0C00:0x06AE:selector], Mem250[0x0C00:0x06AC:word16]) : word32)
  Class: Eq_353
  DataType: (ptr code)
  OrigDataType: (ptr code)
T_360: (in msdos_set_interrupt_vector(0x1B, 0x0C00->w06AC) : void)
  Class: Eq_360
  DataType: void
  OrigDataType: void
T_361: (in msdos_flush_buffer_and_read_stdin : ptr32)
  Class: Eq_361
  DataType: (ptr Eq_361)
  OrigDataType: (ptr (fn T_365 (T_364)))
T_362: (in signature of msdos_flush_buffer_and_read_stdin : void)
  Class: Eq_361
  DataType: (ptr Eq_361)
  OrigDataType: 
T_363: (in al : byte)
  Class: Eq_363
  DataType: byte
  OrigDataType: 
T_364: (in 0xFF : byte)
  Class: Eq_363
  DataType: byte
  OrigDataType: byte
T_365: (in msdos_flush_buffer_and_read_stdin(0xFF) : byte)
  Class: Eq_365
  DataType: byte
  OrigDataType: byte
T_366: (in msdos_display_string : ptr32)
  Class: Eq_366
  DataType: (ptr Eq_366)
  OrigDataType: (ptr (fn T_371 (T_370)))
T_367: (in signature of msdos_display_string : void)
  Class: Eq_366
  DataType: (ptr Eq_366)
  OrigDataType: 
T_368: (in ds_dx : (ptr char))
  Class: Eq_368
  DataType: (ptr char)
  OrigDataType: 
T_369: (in 0x06B0 : word16)
  Class: Eq_369
  DataType: word16
  OrigDataType: word16
T_370: (in SEQ(ds_247, 0x06B0) : word32)
  Class: Eq_368
  DataType: (ptr char)
  OrigDataType: (ptr char)
T_371: (in msdos_display_string(&ds_247->b036C + 836) : void)
  Class: Eq_371
  DataType: void
  OrigDataType: void
T_372:
  Class: Eq_372
  DataType: Eq_372
  OrigDataType: (struct 0001 (0 T_14 t0000))
T_373:
  Class: Eq_372
  DataType: Eq_372
  OrigDataType: (struct 0001 (0 T_18 t0000))
T_374:
  Class: Eq_374
  DataType: byte
  OrigDataType: (struct 0001 (0 T_73 t0000))
T_375:
  Class: Eq_375
  DataType: byte
  OrigDataType: (struct 0001 (0 T_151 t0000))
T_376:
  Class: Eq_375
  DataType: byte
  OrigDataType: (struct 0001 (0 T_191 t0000))
T_377:
  Class: Eq_185
  DataType: byte
  OrigDataType: (struct 0001 (0 byte b0000))
T_378:
  Class: Eq_378
  DataType: byte
  OrigDataType: (struct 0001 (0 T_319 t0000))
*/
typedef struct Globals {
	struct Eq_212 * ptrC000;	// C000
} Eq_1;

typedef struct Eq_2 {
	word16 w0103;	// 103
	ui16 w0105;	// 105
	word16 w0107;	// 107
	Eq_372 a0109[];	// 109
	byte a0526[];	// 526
} Eq_2;

typedef struct Eq_3 {	// size: 1 1
	word16 w0000;	// 0
} Eq_3;

typedef struct Eq_17 {	// size: 1 1
	word16 w0000;	// 0
} Eq_17;

typedef struct Eq_34 {
	word16 w002C;	// 2C
	byte a0080[];	// 80
	byte b036C;	// 36C
	byte b06C1;	// 6C1
	byte a06C2[];	// 6C2
	word16 w06CE;	// 6CE
	word16 w06D0;	// 6D0
	struct Eq_34 * ptr06D2;	// 6D2
	byte a06D4[];	// 6D4
	byte b0714;	// 714
	byte b0717;	// 717
} Eq_34;

typedef struct Eq_35 {
	struct Eq_34 * ptr0815;	// 815
} Eq_35;

typedef void (Eq_44)(char *);

typedef byte (Eq_51)();

typedef void (Eq_58)(byte);

typedef void (Eq_78)(ui8);

typedef void (Eq_86)(byte);

typedef bool (Eq_92)(Eq_34 *, word16, ptr16);

typedef byte (Eq_103)();

typedef bool (Eq_108)(byte, Eq_34 *, word16);

typedef word32 (Eq_206)(byte);

typedef struct Eq_211 {
} Eq_211;

typedef struct Eq_212 {
	word16 w0459;	// 459
	struct Eq_226 * ptr045B;	// 45B
	word16 w051E;	// 51E
	struct Eq_240 * ptr0520;	// 520
	word16 w06AC;	// 6AC
	struct Eq_211 * ptr06AE;	// 6AE
} Eq_212;

typedef word32 (Eq_221)(byte);

typedef struct Eq_226 {
} Eq_226;

typedef word32 (Eq_235)(byte);

typedef struct Eq_240 {
} Eq_240;

typedef void (Eq_248)(byte, code *);

typedef void (Eq_260)(byte, code *);

typedef void (Eq_272)(byte, code *);

typedef void (Eq_284)(byte, code *);

typedef bool (Eq_301)(byte, word32, ptr32);

typedef void (Eq_328)(byte, code *);

typedef void (Eq_339)(byte, code *);

typedef void (Eq_350)(byte, code *);

typedef byte (Eq_361)(byte);

typedef void (Eq_366)(char *);

typedef struct Eq_372 {	// size: 1 1
	word16 w0000;	// 0
} Eq_372;

