// SPIDEY.c
// Generated by decompiling SPIDEY.COM
// using Reko decompiler version 0.8.0.0.

#include "SPIDEY.h"

// 0C00:0100: void fn0C00_0100(Register (ptr Eq_2) ds)
void fn0C00_0100(Eq_2 * ds)
{
	struct Eq_3 Eq_2::* di_16 = Eq_2::a0109;
	word16 cx_17 = ds->w0107;
	word16 ax_18 = 0x00;
	ui16 bx_10 = 0x00;
	do
	{
		ax_18 = ax_18 + (ds->*di_16).w0000;
		bx_10 = bx_10 ^ (ds->*di_16).w0000;
		di_16 = di_16 + 0x01;
		cx_17 = cx_17 - 0x01;
	} while (cx_17 != 0x00);
	if (ax_18 != ds->w0103 || bx_10 != ds->w0105)
	{
		byte Eq_2::* di_33 = Eq_2::a0526;
		do
		{
			ui8 dl_41 = (ds->*di_33 ^ 77) - 0x59;
			msdos_write_console_char(dl_41);
			di_33 = di_33 + 0x01;
		} while (dl_41 != 0x00);
		msdos_terminate(~0x00);
	}
	else
	{
		ss->ptr0815 = cs;
		struct Eq_34 * ds_56 = ss->ptr0815;
		ds_56->b036C = 0x0D;
		msdos_display_string(ds_56->a0080 + 0x008A);
		byte al_63 = msdos_character_input_without_echo();
		if (al_63 != 0x03 && al_63 != 0x1B)
		{
			ss->ptr0815 = cs;
			struct Eq_34 * es_94 = ss->ptr0815;
			word16 bx_105 = 0x81;
			do
			{
				word16 bx_300 = bx_105;
			} while (msdos_resize_memory_block(es_94, bx_300 + 0x01, out bx_105));
			ds_56->b0714 = ds_56->b0714 + msdos_get_current_default_drive();
			msdos_get_current_directory(0x00, ds_56, 0x0100);
			byte Eq_34::* di_116 = &Eq_34::b0717;
			if (ds_56->b0717 != 0x00)
			{
				word16 cx_282 = 0x0100;
				while (cx_282 != 0x00)
				{
					di_116 = di_116 + 0x01;
					cx_282 = cx_282 - 0x01;
					if (0x00 != es_94->*di_116)
						break;
				}
				ds_56->*(di_116 - 0x01) = 0x5C;
			}
			byte Eq_34::* si_124 = &Eq_34::b06C1;
			word16 cx_125 = 0x00;
			do
			{
				cx_125 = cx_125 + 0x01;
				si_124 = si_124 + 0x01;
			} while (ds_56->*si_124 != 0x00);
			byte Eq_34::* si_136 = Eq_34::a06C2;
			while (cx_125 != 0x00)
			{
				es_94->*di_116 = ds_56->*si_136;
				si_136 = si_136 + 0x01;
				di_116 = di_116 + 0x01;
				cx_125 = cx_125 - 0x01;
			}
			ss->ptr0815 = cs;
			ds_56->ptr06D2 = ss->ptr0815;
			ds_56->w06D0 = 0x06D4;
			ds_56->w06CE = ds_56->w002C;
			ss->ptr0815 = cs;
			struct Eq_34 * es_158 = ss->ptr0815;
			ss->ptr0815 = cs;
			struct Eq_34 * ds_163 = ss->ptr0815;
			byte Eq_34::* si_166 = Eq_34::a0080;
			byte Eq_34::* di_167 = Eq_34::a06D4;
			word16 cx_173 = (word16) ds_163->a0080[0x00] + 0x02;
			while (cx_173 != 0x00)
			{
				es_158->*di_167 = ds_163->*si_166;
				si_166 = si_166 + 0x01;
				di_167 = di_167 + 0x01;
				cx_173 = cx_173 - 0x01;
			}
			ss->ptr0815 = cs;
			word32 es_bx_192 = msdos_get_interrupt_vector(0x1B);
			0x0C00->ptr06AE = SLICE(es_bx_192, selector, 16);
			0x0C00->w06AC = (word16) es_bx_192;
			ss->ptr0815 = cs;
			word32 es_bx_202 = msdos_get_interrupt_vector(0x10);
			0x0C00->ptr045B = SLICE(es_bx_202, selector, 16);
			0x0C00->w0459 = (word16) es_bx_202;
			ss->ptr0815 = cs;
			word32 es_bx_212 = msdos_get_interrupt_vector(0x09);
			0x0C00->ptr0520 = SLICE(es_bx_212, selector, 16);
			0x0C00->w051E = (word16) es_bx_212;
			ss->ptr0815 = cs;
			msdos_set_interrupt_vector(0x10, &ss->ptr0815->b036C + 0x0034);
			ss->ptr0815 = cs;
			msdos_set_interrupt_vector(0x09, &ss->ptr0815->b036C + 0x00F1);
			ss->ptr0815 = cs;
			msdos_set_interrupt_vector(0x1B, &ss->ptr0815->b036C + 0x0033);
			ss->ptr0815 = cs;
			msdos_set_interrupt_vector(0x23, &ss->ptr0815->b036C + 0x0033);
			ss->ptr0815 = cs;
			struct Eq_34 * ds_247 = ss->ptr0815;
			ss->ptr0815 = cs;
			if (!msdos_exec(0x00, &ds_247->b0714, &ss->ptr0815->w06CE))
				msdos_display_string(&ds_247->b036C + 0x0344);
			msdos_set_interrupt_vector(0x10, 0x0C00->w0459);
			msdos_set_interrupt_vector(0x09, 0x0C00->w051E);
			msdos_set_interrupt_vector(0x1B, 0x0C00->w06AC);
			msdos_flush_buffer_and_read_stdin(~0x00);
		}
		msdos_terminate(0x00);
	}
}

